import Head from 'next/head'


import { Flex, Heading, Icon, VStack, Stack, StackDivider, Box, Text, SimpleGrid } from "@chakra-ui/react";


import Header from "@/components/Header";
import Footer from "@/components/Footer";
import EntryForm from '@/components/EntryForm';
import ListEntries from '@/components/ListEntries';



function PotentialOption({content}: {content: string}) {
    return (
        <Box>
            <Text textColor={"blue"} fontWeight={"600"} fontSize={"4xl"}>{content}</Text>
        </Box>
    )
}

export default function Morning(props) {

    
    
    return (
        <>
            <Head>
            <title>OptiOreo - Morning</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            </Head>

            <Flex direction={"column"} flex="1" py={12} >
                <Header/>

                <Heading pt={"20"} fontSize={"7xl"} textAlign={"center"} >
                    {/* Morning <Icon as={BiSmile} /> */}
                    Morning of {new Date().toLocaleDateString("en-US", {weekday: "long", month: "long", day: "numeric", year: "numeric"})}
                </Heading>

                <SimpleGrid columns={2} spacing={10} m={"20"}>

                    <VStack spacing={4}>
                        <Heading textAlign={"center"} fontSize={"6xl"} m={"20"} >
                            What do you want to do today?
                        </Heading>

                        <VStack spacing={8} divider={<StackDivider borderColor={"blue.100"}/>}  mx={"20"} >
                            <PotentialOption content={"Appreciate someone"}/>
                            <PotentialOption content={"Appreciate yourself"}/>
                        </VStack>
                    </VStack>
                    
                    <EntryForm />

                </SimpleGrid>
            
                <ListEntries />

                <Footer />
            </Flex>
        </>
    )
}
