import Head from 'next/head'

import { Flex, Heading } from "@chakra-ui/react";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

export default function DailyStatus(props) {
    return (
        <>
            <Head>
            <title>OptiOreo</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            </Head>

            <Flex direction={"column"} flex="1">
            <Header/>

            <Heading mt={"20"} fontSize={"7xl"} textAlign={"center"} >
                Night of {new Date().toLocaleDateString("en-US", {weekday: "long", month: "long", day: "numeric", year: "numeric"})}
            </Heading>

            <Footer />
            </Flex>
        </>
    )
}

// form collect data